version: '2'
services:
    jhspringsecurity-app:
        image: jhspringsecurity
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhspringsecurity-mysql:3306/jhspringsecurity?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhspringsecurity-mysql:
        extends:
            file: mysql.yml
            service: jhspringsecurity-mysql
